# docker-compose.yml

services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    ports:
      - "5001:5001"
    volumes:
      - ./mlflow-artifacts:/home/pooria/project/bike-retrain-mlops/mlflow-artifacts
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5001
      --backend-store-uri sqlite:////home/pooria/project/bike-retrain-mlops/mlflow-artifacts/mlflow.db
      --default-artifact-root /home/pooria/project/bike-retrain-mlops/mlflow-artifacts/artifacts
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5001/health')"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5001
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./mlflow-artifacts:/home/pooria/project/bike-retrain-mlops/mlflow-artifacts
    depends_on:
      mlflow:
        condition: service_healthy
    restart: on-failure

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

volumes:
  mlflow_data:
  grafana_data: