# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "setuptools<81"
          pip install -r requirements.txt

      - name: Download dataset
        run: |
          mkdir -p data/raw data/monthly_chunks logs
          curl -L -o data/raw/hour.csv \
            "https://raw.githubusercontent.com/muditp19/UCI_Bike-sharing-dataset/master/hour.csv"
          python -m src.data.data_prep

      - name: Run tests
        run: |
          python -m pytest src/tests/ -v --tb=short